GET http://localhost:5000/api/v1/user/ffsfsdfdsfdsfdsfdsf

###
POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
    "email": "admin3@gmail.com",
    "password": "123123"
    
}

###
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
    "email": "admin3@gmail.com",
    "password": "123123"
}

###
GET http://localhost:5000/api/v1/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhZG1pbjNAZ21haWwuY29tIiwicm9sZV9jb2RlIjoiUjMiLCJpYXQiOjE2NjUyODM2NzgsImV4cCI6MTY2NTI4MzY4M30.NgbIKgKycadfOC_bG1C1ofRAU7QDAjq1HRhcdehVYes



###
GET http://localhost:5000/api/v1/insert/

###
GET http://localhost:5000/api/v1/book/

